### ISSUE TITLE
question about number of movies to clustering

### ISSUE THREAD

**Issue by nmotevallian** [digantamisra98/KMeans-Movie-Ratings#1]
Hi, I'm working on clustering in recommender systems and in your code I want to know, if I want to cluster all movies(not 1000movies that you considered), what should I do? Is it possible or accuracy will be low because of the sparsity of this matrix? Do you know how can I cluster all movies by k-means according to their ratings?

**Comment by digantamisra98** [comment]
@niusha1373 apologies for my late response. By all movies, do you mean the complete [Movie Lens](https://grouplens.org/datasets/movielens/) data? I don't believe the accuracy will take any significant hit because of sparse matrix but I'd like to give it a try. However, I might not be having enough time to experiment with the same right now, I'll revisit this when time permits, you're welcome to use the code as boilerplate or submit a PR if you have any significant findings. Thanks.
